[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
ffi = true

[rpc_endpoints]
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

[etherscan]
goerli = { key = "${ETHERSCAN_API_KEY}" }

# Remappings in remappings.txt

# See more config options https://github.com/gakonst/foundry/tree/master/config
